name = "Hugo Fresh for eScriptorium"
license = "MIT"
licenselink = "https://github.com/mittagessen/hugo-fresh/blob/master/LICENSE.md"
description = "A Hugo adaptation of the Fresh theme from CSS Ninja"
homepage = "https://github.com/mittagessen/hugo-fresh"
tags = ["responsive", "one page", "light", "onepage", "company", "clean", "landing page"]
features = []
min_version = "0.45"

[author]
  name = "Stefan M."
  homepage = "https://github.com/StefMa"
